services:
  - type: web
    name: mec-backend
    runtime: node
    region: singapore
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: "mongodb+srv://officialtechnofixer_db_user:TECHNO%402004@cluster0.mozv4cd.mongodb.net/uafms?retryWrites=true&w=majority&appName=Cluster0"
      - key: JWT_SECRET
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: JWT_EXPIRE
        value: "30d"
      - key: PORT
        value: "10000"
